GET http://localhost:3003/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer ...

{
  "title": "Authorization is Important, Really",
  "author": "Some Guy On the Internet",
  "url": "https://localhost",
  "likes": 42
}

###

DELETE http://localhost:3003/api/blogs/6366cd75d209651cae6d3ca6 HTTP/1.1
Authorization: bearer ...